
services:
  labexamns-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labexamns-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://<IP_Privada_MONGO>:27017/lab_exams_db