version: '3.8'

services:
  labexamns-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labexamns-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://<IP_PUBLICA_MONGO>:27017/lab_exams_db